
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: my_database
    container_name: php-container

  db:
    image: mysql:latest
    container_name: db-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./src/BDD/bdd.sql:/docker-entrypoint-initdb.d/bdd.sql

volumes:
  db-data: